[package]
name = "know-hub_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
clickhouse = "0.11.6"
jsonwebtoken = "9.3.0"
reqwest = "0.12.5"
serde = "1.0.204"
serde_json = "1.0.120"
